version: "3"
services:
  api:
    build: .
    image: cloud-auth-api
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_SECRET: ${COOKIE_SECRET}
      HCAPTCHA_SECRET: ${HCAPTCHA_SECRET}
      DIRECT_URL: ${DIRECT_URL}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
  redis:
    image: redis:6.2.12
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    ports:
      - "6379:6379"
