version: "3"
services:
  api:
    image: cloud-auth-api
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_SECRET: ${COOKIE_SECRET}
      DIRECT_URL: ${DIRECT_URL}
      DATABASE_URL: ${DATABASE_URL}
