name: release

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "terraform/**"

permissions:
  contents: write

jobs:
  release:
    runs-on:
      group: ubuntu-runners
    outputs:
      version: ${{ steps.clean_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Cocogitto release"
        id: release
        uses: cocogitto/cocogitto-action@v3
        with:
          check: true
          check-latest-tag-only: true
          release: true
          git-user: 'github-actions[bot]'
          git-user-email: "github-actions[bot]@users.noreply.github.com"

      - name: "Update Github release notes"
        uses: softprops/action-gh-release@v1
        with:
          #body_path: GITHUB_CHANGELOG.md
          body: "Generated Release"
          tag_name: ${{ steps.release.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: clean_version
        run: |
          version=$(echo "${{ steps.release.outputs.version }}" | sed 's/v//g')
          echo "version=$version" >> $GITHUB_OUTPUT

  build-container:
    runs-on:
      group: ubuntu-runners
    needs:
      - release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Authenticate with ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/cloud-auth-api
            walletconnect/cloud-auth-api,enable=false
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ needs.release.outputs.version }}

      # Setup Buildkit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
